name: Update helm chart

on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
        description: "The target repository"
      app_version:
        type: string
        required: true
        description: "The app version"
    secrets:
      TOKEN:
        required: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    name: "Update helm chart app version"
    steps:
      - name: Show inputs
        run: |
          echo "::group::inputs"
          echo 'repo: ${{ inputs.repo }}'
          echo 'app_version: ${{ inputs.app_version }}'
          echo '::endgroup::'
      - name: Get target repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          token: ${{ secrets.TOKEN }}
      - name: Update app version
        run: yq -i '.appVersion = "${{ inputs.app_version }}"' Chart.yaml
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore: update app version to ${{ inputs.app_version }}"
